[package]
name = "gc-email-validator"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false
default-run = "gc-email-validator"

[dependencies]
idna.workspace = true
lambda_http.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[[bin]]
name = "gc-email-validator"
path = "src/cli.rs"

[[bin]]
name = "gc-email-validator-lambda"
path = "src/main.rs"
